version: '3.9'
services:
  avantio-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: henriquesena/bubble-server:0.0.1
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
    container_name: bubble-server
    command: ["npm", "run", "start:prod"]